= New Java Features
:revealjs_theme: night
:source-highlighter: highlight.js
:highlightjsdir: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.11.1/build
:highlightjs-theme: https://cdn.jsdelivr.net/npm/highlight.js@11.11.1/styles/a11y-dark.css
:revealjs_margin: 0.0
:revealjs_width: 1280
:revealjs_height: 720

Since Java 9

// Focus is new language features, or significant APIs

== 9: Java Modules

* This could be a whole session on its own
* Not used in Liberty
* Many API jars will now have a module-info.class

== Private methods on interfaces

* Allows sharing of common code between `default` methods

== Compile for older versions

* `-release` option
* Targets older bytecode (as before with -source and -target)
* Checks you don't use newer classes (new)

== Factory methods for collections

* e.g. `List.of(1, 2, 3)`
* e.g. `Map.of("foo", new Foo(), "bar", new Bar())`
* Created collections are immutable

[.notes]
--
May have used `Arrays.asList` for this before. Do note that `List.of` is unmodifiable.
--

== 10: Local variable type inference

[source,java]
----
var list = new ArrayList<String>(); // Infers ArrayList<String>
var stream = list.stream();         // Infers Stream<String>
----

[.notes]
--
JEP286

Only applicable to local variables with initializers, and index variables in for-loops.

Few cases (e.g. Lambdas) where it's impossible to infer a type and others where you might not want the inferred type (e.g. you might want `List<String>`).
--

=== Type inference

[source, java]
----
void removeOdd(Map<String, List<Integer>> map) {
    for (Iterator<Entry<String, List<Integer>>> i = map.entrySet().iterator(); i.hasNext();) {
        Entry<String, List<Integer>> entry = i.next();
        List<Integer> numList = entry.getValue();
        if (numList.stream().filter(i -> i % 2 != 0).findAny().isPresent()) {
            i.remove();
        }
    }
}
----

=== Type inference

[source, java]
----
void removeOdd(Map<String, List<Integer>> map) {
    for (var i = map.entrySet().iterator(); i.hasNext();) {
        var entry = i.next();
        var numList = entry.getValue();
        if (numList.stream().filter(i -> i % 2 != 0).findAny().isPresent()) {
            i.remove();
        }
    }
}
----

== 11: New HTTP Client

* `java.net.http` package
* Can be used instead of `HttpURLConnection` or Apache `HttpClient`
* Supports HTTP/1.1 and HTTP/2

== 14: Switch Expressions

New syntax for `switch`

[source, java]
----
switch (day) {
    case MONDAY, FRIDAY, SUNDAY -> System.out.println(6);
    case TUESDAY                -> System.out.println(7);
    case THURSDAY, SATURDAY     -> System.out.println(8);
    case WEDNESDAY              -> System.out.println(9);
}
----

Old syntax still supported

=== No fallthrough

[source, java]
----
switch (x) {
    case A:
    case B:
        // Stuff for A and B
        break;
    case C:
        // Stuff for C
        break;
}
----

[source, java]
----
switch (x) {
    case A, B -> {/* Stuff for A and B"*/ }
    case C    -> {/* Stuff for C */};
}
----

[.notes]
--
For old switch, you can do fallthrough like this and use `break` to mark the end of each block.

It's actually possible to put stuff between case A and B here which will run for A and not for B, but then the stuff after B will run for both.

That's rarely useful, usually it's because you forgot to put `break` in.

No longer! The new switch syntax does allow you to have several inputs run the same code, but it does it like this.

Here we also demonstrate that you can use blocks for each case.
--

=== Can return a value

[source, java]
----
int numLetters = switch (day) {
    case MONDAY, FRIDAY, SUNDAY -> 6;
    case TUESDAY                -> 7;
    case THURSDAY, SATURDAY     -> 8;
    case WEDNESDAY              -> 9;
};
----

When returning a value, the switch must be _exhaustive_.

[.notes]
--
Note there's no return here, you just put the value you want to return.

If you need to do something more complex before you return then...
--

=== `yield` to return a value from a block

[source, java]
----
int j = switch (day) {
    case MONDAY  -> 0;
    case TUESDAY -> 1;
    default      -> {
        int k = day.toString().length();
        int result = f(k);
        yield result;
    }
};
----

== 15: Hidden classes

* For frameworks which dynamically define classes
* Prevents discovery or loading by name
* Allows class to be unloaded while parent Classloader is still in use

== 15: Text Blocks

* Easy quoting around multi-line string literals
* Before:

[source, java]
----
String query = "SELECT \"EMP_ID\", \"LAST_NAME\" FROM \"EMPLOYEE_TB\"\n" +
               "WHERE \"CITY\" = 'INDIANAPOLIS'\n" +
               "ORDER BY \"EMP_ID\", \"LAST_NAME\";\n";
----
* After:

[source, java]
----
String query = """
               SELECT "EMP_ID", "LAST_NAME" FROM "EMPLOYEE_TB"
               WHERE "CITY" = 'INDIANAPOLIS'
               ORDER BY "EMP_ID", "LAST_NAME";
               """;
----

=== Indentation

* Common leading whitespace is removed so that text can indented sensibly without compromising formatting

[source, java]
----
String html = """
            <html>
                <body>
                    <p>Hello, world</p>
                </body>
            </html>
            """;
----

=== Indentation

Will result in

[source, html]
----
<html>
    <body>
        <p>Hello, world</p>
    </body>
</html>
----

== 16: Pattern Matching for instanceof

* Combines an instanceof check with a cast

Before:
[source,java]
----
if (obj instanceof String) {
    String s = (String) obj;    // grr...
    ...
}
----

After:
[source,java]
----
if (obj instanceof String s) {
    // Let pattern matching do the work!
    ...
}
----

== 16: Records

* Concise syntax for simple, immutable data classes
* Can think of them as typed tuples

=== Without Records

[source.stretch, java]
----
class Point {
    private final int x;
    private final int y;

    Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    int x() { return x; }
    int y() { return y; }

    public boolean equals(Object o) {
        if (!(o instanceof Point)) return false;
        Point other = (Point) o;
        return other.x == x && other.y == y;
    }

    public int hashCode() {
        return Objects.hash(x, y);
    }

    public String toString() {
        return String.format("Point[x=%d, y=%d]", x, y);
    }
}
----

[.notes]
--
A good practise immutable Java class with two values might look like this.
--

=== With records

[source, java]
----
record Point(int x, int y) { }
----

=== Record features

- `private final` fields
- accessor methods
  - same name as field (i.e, `x()` and `y()`)
- `equals` and `hashCode`
- `toString`

[.notes]
--
This is what records give you automatically
--

=== Record restrictions

- Cannot `extend` another class
  - but can implement interfaces
- Always `final` (can't be extended)
- Cannot declare additional fields
- No `native` methods

== 17: Sealed classes

- Declaration on an interface or class limiting which classes can extend or implement it

[source,java]
----
public abstract sealed class Shape
    permits Circle, Rectangle, Square { ... }
----

== 18: Snippets in Javadoc

Lots of Javadoc comments have examples included like this:
[source,java]
----
/**
 * Example:
 * <pre>{@code
 *   Foo.bar();
 * }</pre>
 */
public void bar();
----

=== New Snippet Syntax

[source,java]
----
/**
 * Example:
 * {@snippet :
 *   Foo.bar();
 * }
 */
----

[.notes]
--
No need to escape characters like `@, <, >, &`

Leading whitespace is stripped (like text blocks we saw earlier)

Limitations:
- Can't use `/* */` comments
- Must have balanced curly braces

More tricks:
--

=== External snippets

[source,java]
----
/**
 * The following code shows how to use {@code Optional.isPresent}:
 * {@snippet file="ShowOptional.java" region="example"}
 */
----

where `ShowOptional.java` is a file containing:

[source,java]
----
public class ShowOptional {
    void show(Optional<String> v) {
        // @start region="example"
        if (v.isPresent()) {
            System.out.println("v: " + v.get());
        }
        // @end
    }
}
----

[.notes]
--
Snippet files live in a separate `snippet-files` directory.

@start and @end to indicate the region for the snippet

Can be edited with full IDE support.

Can be put on your test classpath for testing.
--

=== Highlighting

[source, java]
----
/**
 * A simple program.
 * {@snippet :
 * class HelloWorld {
 *     public static void main(String... args) {
 *         System.out.println("Hello World!");      // @highlight substring="println"
 *     }
 * }
 * }
 */
----

=== Modifying

[source, java]
----
/**
 * A simple program.
 * {@snippet :
 * class HelloWorld {
 *     public static void main(String... args) {
 *         System.out.println("Hello World!");  // @replace regex='".*"' replacement="..."
 *     }
 * }
 * }
 */
----

[source, java]
----
class HelloWorld {
    public static void main(String... args) {
        System.out.println(...);
    }
}
----

=== Linking

[source, java]
----
/**
 * A simple program.
 * {@snippet :
 * class HelloWorld {
 *     public static void main(String... args) {
 *         System.out.println("Hello World!");  // @link substring="System.out" target="System#out"
 *     }
 * }
 * }
 */
----

[.notes]
--
Target is the same form as the standard `{@link }` tag
--

== 21: Record Patterns

* Combines an `instanceof` check with the deconstruction of a record

[source,java]
----
static void printSum(Object obj) {
    if (obj instanceof Point p) {
        int x = p.x();
        int y = p.y();
        System.out.println(x+y);
    }
}
----

[source,java]
----
static void printSum(Object obj) {
    if (obj instanceof Point(int x, int y)) {
        System.out.println(x+y);
    }
}
----

== 21: Pattern matching for switch

* Allows several `instanceof` checks to be expressed as a `switch`

[source,java]
----
static String formatterPatternSwitch(Object obj) {
    return switch (obj) {
        case Integer i -> String.format("int %d", i);
        case Long l    -> String.format("long %d", l);
        case Double d  -> String.format("double %f", d);
        case String s  -> String.format("String %s", s);
        default        -> obj.toString();
    };
}
----

// TODO: Can you mix and match values?

=== Null allowed

[source,java]
----
static void testFooBarNew(String s) {
    switch (s) {
        case null         -> System.out.println("Oops");
        case "Foo", "Bar" -> System.out.println("Great");
        default           -> System.out.println("Ok");
    }
}
----

== 22: Unnamed variables

* Allows deliberately declaring a variable you don't want to use

[source,java]
----
static int count(Iterable<Order> orders) {
    int total = 0;
    for (Order _ : orders)    // Unused variable
        total++;
    return total;
}
----

=== Also in switch patterns

[source,java]
----
Ball ball = ...
switch (ball) {
    case RedBall   red   -> process(red);
    case BlueBall  blue  -> process(blue);
    case GreenBall _     -> stopProcessing();
}
----

== 23: Markdown Javadoc Comments

[source,java]
----
/**
 * Super-important method for very critical things.
 * <p>
 * When calling this method it's essential to:
 * <ul>
 * <li>acquire the lock while retrieving the widget
 * <li>return every widget that is retrieved
 * <li>acquire the lock while returning the widget
 * 
 * @see com.example.Widget
 */
----

=== Markdown Javadoc Comments

[source,java]
----
/// Super-important method for very critical things.
/// 
/// When calling this method it's essential to:
/// 
/// - acquire the lock while retrieving the widget
/// - return every widget that is retrieved
/// - acquire the lock while returning the widget
/// 
/// @see com.example.Widget
----

== 24: Class-File API

New API for reading and writing class files directly: `java.lang.classfile`

Similar use-cases as the ASM library.

== 24: Stream gatherers

Allows for custom complex operations in the middle of a stream.

Similar to `Collector` but for intermediate operations.

=== Custom operations

[source,java]
----
Stream.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
      .filter(i -> i % 2 == 0)       // Only even numbers
      .fixedWindow(2)                // Pair them up <-- doesn't exist
      .map(i -> i.get(0) + i.get(1)) // Sum each pair
      .toList();                     // Collect in a list
----

=== Built-in gatherers

[source,java]
----
Stream.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
      .filter(i -> i % 2 == 0)          // Only even numbers
      .gather(Gatherers.fixedWindow(2)) // Pair them up
      .map(i -> i.get(0) + i.get(1))    // Sum each pair
      .toList();                        // Collect in a list
----

== 25: Flexible Constructor Bodies

Previously `super` or `this` had to be the first thing called in a constructor

[source,java]
----
public MyClass(String name, int count) {
    String identifier = computeItentifier(name, count); // NOT ALLOWED
    super(identifier, name);
}
----

=== Flexible Constructor Bodies

You could kind of hack around it a bit by calling static methods to calculate the parameters

[source,java]
----
public MyClass(String name, int count) {
    super(computeItentifier(name, count), name);
}
----

=== Flexible Constructor Bodies

Now you're allowed to do a limited number of things before calling `this` or `super`

* You still can't:
** Use `this` to refer to the current instance
** Access fields of this or a super class
** Call non-static methods of this or a super class

* However, you may:
** Use simple assignment to uninitialized fields

== 25: Scoped Values

* Alternative to `ThreadLocal` for passing context.

=== 25: Thread Local Example

[source,java]
----
private static final ThreadLocal<MyContext> CONTEXT = new ThreadLocal<>();

void doGet(ServletRequest request, ServletResponse response) {
    CONTEXT.set(createContext(request));
    try {
        handle(request, response);
    } finally {
        CONTEXT.remove()
    }
}

// Called from within handle()
public MyContext getContext() {
    return CONTEXT.get();
}
----

=== 25: ScopedValue Example

[source,java]
----
private static final ScopedValue<MyContext> CONTEXT = ScopedValue.newInstance();

void doGet(ServletRequest request, ServletResponse response) {
    MyContext context = createContext(request);
    ScopedValue.where(CONTEXT, context)
               .run(() -> handle(request, response));
}

// Called from within handle()
public MyContext getContext() {
    return CONTEXT.get();
}
----

=== 25: ThreadLocal vs. ScopedValue

* `ThreadLocal`
** Unlimited lifetime
** Mutable
* `ScopedValue`
** Limited lifetime (can't forget to call `remove()`)
** Immutable
*** Can be rebound in a new scope
